# This .bashrc is mostly generated.
# Some of it is boilerplate that comes with the OS installation.
# Some of it is generated by installing and activating conda.
# Some of it towards the end is my customization, including things that
# are needed for arkouda, and things that are just my personal taste.

# $HOME/.bashrc: executed by bash(1) for non-login shells.
# see /usr/share/doc/bash/examples/startup-files (in the package bash-doc)
# for examples

# If not running interactively, don't do anything
case $- in
    *i*) ;;
      *) return;;
esac

# things having to do with history

HISTCONTROL=ignoreboth
shopt -s histappend
HISTSIZE=1000
HISTFILESIZE=2000

# check the window size after each command and, if necessary,
# update the values of LINES and COLUMNS.

shopt -s checkwinsize

# set variable identifying the chroot you work in (used in the prompt below)

if [ -z "${debian_chroot:-}" ] && [ -r /etc/debian_chroot ]; then
    debian_chroot=$(cat /etc/debian_chroot)
fi

# set a fancy prompt (non-color, unless we know we "want" color)
case "$TERM" in
    xterm-color|*-256color) color_prompt=yes;;
esac

# uncomment for a colored prompt, if the terminal has the capability; turned
# off by default to not distract the user: the focus in a terminal window
# should be on the output of commands, not on the prompt

force_color_prompt=yes

if [ -n "$force_color_prompt" ]; then
    if [ -x /usr/bin/tput ] && tput setaf 1 >&/dev/null; then
	# We have color support; assume it's compliant with Ecma-48
	# (ISO/IEC-6429). (Lack of such support is extremely rare, and such
	# a case would tend to support setf rather than setaf.)
	color_prompt=yes
    else
	color_prompt=
    fi
fi

# after some experimentation, I know this is how I want the prompt to look

PS1='${debian_chroot:+($debian_chroot)}\u@\h:\w\ $ '

# If this is an xterm set the title to user@host:dir

case "$TERM" in
xterm*|rxvt*)
    PS1="\[\e]0;${debian_chroot:+($debian_chroot)}\u@\h: \w\a\]$PS1"
    ;;
*)
    ;;
esac

# enable color support of ls and also add handy aliases

if [ -x /usr/bin/dircolors ]; then
    test -r $HOME/.dircolors && eval "$(dircolors -b $HOME/.dircolors)" || eval "$(dircolors -b)"
    alias ls='ls --color=auto'
    alias grep='grep --color=auto'
    alias fgrep='fgrep --color=auto'
    alias egrep='egrep --color=auto'
fi

# Add an "alert" alias for long running commands.  Use like so:

alias alert='notify-send --urgency=low -i "$([ $? = 0 ] && echo terminal || echo error)" "$(history|tail -n1|sed -e '\''s/^\s*[0-9]\+\s*//;s/[;&|]\s*alert$//'\'')"'

# enable programmable completion features (you don't need to enable
# this, if it's already enabled in /etc/bash.bashrc and /etc/profile
# sources /etc/bash.bashrc).

if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

# Except for the PS1 variable, all of the above is boilerplate stuff created elsewhere.
# What follows are my customizations.

# Environment variables for Chapel and Arkouda

export CHPL_HOME=$HOME/chapel-2.6.0
export PATH=$PATH:$CHPL_HOME/bin/linux64-86_64
export PYTHONPATH=$PYTHONPATH:$HOME/projects/arkouda
export ARKOUDA_HOME=$HOME/projects/arkouda
export ARKOUDA_QUICK_COMPILE=true
export ARKOUDA_SKIP_CHECK_DEPS=True
source $CHPL_HOME/util/setchplenv.bash

export CHPL_LLVM=system
export CHPL_GMP=bundled
export CHPL_TARGET_CPU=native
export CHPL_COMM=none
export CHPL_HOST_MEM=jemalloc
export CHPL_RE2=bundled

#  My editor of choice

export EDITOR=vim

# Environment changes, for enabling Gasnet and debugmode

setGasnet() {
  export CHPL_COMM=gasnet
  export GASNET_SPAWNFN=L
  export GASNET_ROUTE_OUTPUT=0
  export CHPL_GASNET_CFG_OPTIONS=--disable-ibv
  export GASNET_QUIET=Y
  export GASNET_MASTERIP=127.0.0.1
  export GASNET_WORKERIP=127.0.0.0
  export CHPL_TEST_TIMEOUT=500
  export CHPL_RT_OVERSUBSCRIBED=yes
  PS1="GAS**$PS1"
}

deGas() {
  if [ "$CHPL_COMM" == "gasnet" ]; then
    export CHPL_COMM=none
    unset GASNET_SPAWNFN
    unset GASNET_ROUTE_OUTPUT
    unset CHPL_GASNET_CFG_OPTIONS
    unset GASNET_QUIET
    unset GASNET_MASTERIP
    unset GASNET_WORKERIP
    unset CHPL_TEST_TIMEOUT
    unset CHPL_RT_OVERSUBSCRIBED
    PS1=${PS1:5}
  fi
}

debugmode() {
    unset ARKOUDA_QUICK_COMPILE
    export CHPL_DEVELOPER=True
    export ARKOUDA_DEVELOPER=True
}

#  Arkouda multi-dimensionality stuff

REGISTER_FILE="$ARKOUDA_HOME/registration-config.json"
multi() {
    cp $ARKOUDA_HOME/.configs/registration-config-multi-dim.json $REGISTER_FILE
}
singe() {
    cp $ARKOUDA_HOME/.configs/registration-config-single-dim.json $REGISTER_FILE
}
dual() {
    cp $HOME/registration-config-dual-dim.json $REGISTER_FILE
}

# Miniconda initialization.

# >>> conda initialize >>>
# !! Contents within this block are managed by 'conda init' !!

__conda_setup="$('$HOME/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
if [ $? -eq 0 ]; then
    eval "$__conda_setup"
else
    if [ -f "$HOME/miniconda3/etc/profile.d/conda.sh" ]; then
        . "$HOME/miniconda3/etc/profile.d/conda.sh"
    else
        export PATH="$HOME/miniconda3/bin:$PATH"
    fi
fi
unset __conda_setup

# <<< conda initialize <<<

conda activate arkouda-dev

# aliases

alias arkk="cd $HOME/projects/arkouda"
alias arkp="cd $HOME/projects/arkouda/arkouda"
alias arkc="cd $HOME/projects/arkouda/src"
alias serv="$HOME/projects/arkouda/arkouda_server"
alias tink="cd $HOME/tinkering"

# and some more

alias p2="python2.7"  # I always install python2; your mileage may vary
alias p3="python3"
alias charm="/snap/bin/pycharm-community"
#alias jup="/snap/bin/jupyterlab-desktop"
alias jup="jupyter-notebook"
alias viz="/snap/bin/code"

# and special cases

alias neaten="$HOME/neaten.sh"
alias nt="$HOME/neaten.sh"
alias tm="terminator -l Multipane &"
alias pyhunt="sh ~/misc/pyhunt.sh"
alias chhunt="sh ~/misc/chhunt.sh"

# git stuff

# sets up `git pr 760`
git config --global alias.pr '!f() { git fetch -fu ${2:-$(git remote |grep ^upstream || echo origin)} refs/pull/$1/head:pr/$1 && git checkout pr/$1; }; f'

# sets up `git pr-clean` to wipe up things in the git pr/### space
git config --global alias.pr-clean '!git for-each-ref refs/heads/pr/* --format="%(refname)" | while read ref ; do branch=${ref#refs/heads/} ; git branch -D $branch ; done'
